# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiYXs6nu2cWFseax9vUzFbw3QdJOe0WB
"""

checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]
postion1 = input().split()
postion2 = input().split()
x1 = int(postion1[0])
y1 = int(postion1[1])
x2 = int(postion2[0])
y2 = int(postion2[1])
canmove = True
if(checkerboard[x2][y2] !=0):
    canmove = False
if(y2==y1 and x2==(x1+1)):
    canmove = True
else:
    canmove = False

if(canmove ==True):
    temp = checkerboard[x2][y2]
    checkerboard[x2][y2] = checkerboard[x1][y1]
    checkerboard[x1][y1] = temp
if(canmove ==True):
    print("Yes")
else:
    print("No")

checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

postion1 = input().split()
postion2 = input().split()
x1 = int(postion1[0])
y1 = int(postion1[1])
x2 = int(postion2[0])
y2 = int(postion2[1])
canmove = True
if(y2==y1 and x2==(x1+1)):
  canmove = True
else:
  canmove = False
if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
    canmove = False


if(canmove ==True):
    temp = checkerboard[x2][y2]
    checkerboard[x2][y2] = checkerboard[x1][y1]
    checkerboard[x1][y1] = temp
if(canmove ==True):
    print("Yes")
else:
    print("No")

checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]
postion1 = input().split()
postion2 = input().split()
x1 = int(postion1[0])
y1 = int(postion1[1])
x2 = int(postion2[0])
y2 = int(postion2[1])
canmove = True
for a in range(-2,3,4):
  for b in range(-1,2,2):
    if(y2==(y1+a) and x2==(x1+b)):
      canmove = True

      break;
    elif(y2==(y1+b) and x2==(x1+a)):
      canmove = True
      break;
    else:
      canmove = False
  if canmove ==True:
    break;


if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
    canmove = False


if(canmove ==True):
    temp = checkerboard[x2][y2]
    checkerboard[x2][y2] = checkerboard[x1][y1]
    checkerboard[x1][y1] = temp

if(canmove ==True):
    print("Yes")
else:
    print("No")

checkerboard =[

[1, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0]

]
postion1 = input().split()
postion2 = input().split()
x1 = int(postion1[0])
y1 = int(postion1[1])
x2 = int(postion2[0])
y2 = int(postion2[1])
canmove = True
for a in range(-1,2,1):
  for b in range(-1,2,1):
    if(y2==(y1+a) and x2==(x1+b)):
      canmove = True

      break;
    elif(y2==(y1+b) and x2==(x1+a)):
      canmove = True
      break;
    else:
      canmove = False
  if canmove ==True:
    break;


if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
    canmove = False


if(canmove ==True):
    temp = checkerboard[x2][y2]
    checkerboard[x2][y2] = checkerboard[x1][y1]
    checkerboard[x1][y1] = temp

if(canmove ==True):
    print("Yes")
else:
    print("No")

checkerboard = [ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]
postion1 = input().split()
postion2 = input().split()
x1 = int(postion1[0])
y1 = int(postion1[1])
x2 = int(postion2[0])
y2 = int(postion2[1])
canmove = True
for a in range(-1,2,1):
  for b in range(-1,2,1):
    if(y2==(y1+a) and x2==(x1+b)):
      canmove = True
      break;

    elif(y2==(y1+b) and x2==(x1+a)):
      canmove = True
      break;
    else:
      canmove = False

  if canmove ==True:
    break;
dif = x2 - x1

if((y1+dif) == y2 and dif>0):
  for a in range(1,dif+1):
    if(checkerboard[x1+a][y1+a] !=0):
      canmove = False

      break
    else:
      canmove = True
if((y1+dif) == y2 and dif<0):

  for a in range(-1,dif-1,-1):

    if(checkerboard[x1+a][y1+a] !=0):
      canmove = False
      break

    else:
      canmove = True

if(x1 == x2):
  dif = y2 - y1
  if(dif<0):
    for a in range(-1,dif-1,-1):
      if(checkerboard[x1][y1+a] !=0):
        canmove = False
        break
  elif(dif>0):
    for a in range(1,dif+1):
      if(checkerboard[x1][y1+a] !=0):
        canmove = False
        break
  else:
    canmove = True
if(y1 == y2):
  dif = x2 - x1
  if(dif<0):
    for a in range(-1,dif-1,-1):
      if(checkerboard[x1+a][y1] !=0):
        canmove = False
        break

  elif(dif>0):
    for a in range(1,dif+1):
      if(checkerboard[x1+a][y1] !=0):
        canmove = False
        break
  else:
    canmove = True




if(canmove ==True):
    print("Yes")
else:
    print("No")

def queen(postion1,postion2,checkerboard):
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
# 如果停在原地，則輸出 No
  if x1 == x2 and y1 == y2:
      print("No")
      exit()

  canmove = True

  # 判斷是否是合法的皇后移動（水平、垂直、對角線）
  if x1 == x2 or y1 == y2 or abs(x2 - x1) == abs(y2 - y1):
      # 檢查水平移動
      if x1 == x2:
          step = 1 if y2 > y1 else -1
          for a in range(y1 + step, y2, step):
              if checkerboard[x1][a] != 0:
                  canmove = False
                  break

      # 檢查垂直移動
      elif y1 == y2:
          step = 1 if x2 > x1 else -1
          for a in range(x1 + step, x2, step):
              if checkerboard[a][y1] != 0:
                  canmove = False
                  break

      # 檢查對角線移動
      else:
          step_x = 1 if x2 > x1 else -1
          step_y = 1 if y2 > y1 else -1
          for a in range(1, abs(x2 - x1)):
              if checkerboard[x1 + a * step_x][y1 + a * step_y] != 0:
                  canmove = False
                  break
  else:
      canmove = False

  # 輸出結果
  print("Yes" if canmove else "No")
def pawn(postion1,postion2,checkerboard):
  postion1 = input().split()
  postion2 = input().split()
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
  canmove = True
  if(y2==y1 and x2==(x1+1)):
    canmove = True
  else:
    canmove = False
  if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
      canmove = False


  if(canmove ==True):
      temp = checkerboard[x2][y2]
      checkerboard[x2][y2] = checkerboard[x1][y1]
      checkerboard[x1][y1] = temp
  if(canmove ==True):
      print("Yes")
  else:
      print("No")
def knight(postion1,postion2,checkerboard):
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
  canmove = True
  for a in range(-2,3,4):
    for b in range(-1,2,2):
      if(y2==(y1+a) and x2==(x1+b)):
        canmove = True

        break;
      elif(y2==(y1+b) and x2==(x1+a)):
        canmove = True
        break;
      else:
        canmove = False
    if canmove ==True:
      break;


  if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
      canmove = False


  if(canmove ==True):
      temp = checkerboard[x2][y2]
      checkerboard[x2][y2] = checkerboard[x1][y1]
      checkerboard[x1][y1] = temp

  if(canmove ==True):
      print("Yes")
  else:
      print("No")
def king( postion1,postion2,checkerboard):
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
  canmove = True
  for a in range(-1,2,1):
    for b in range(-1,2,1):
      if(y2==(y1+a) and x2==(x1+b)):
        canmove = True

        break;
      elif(y2==(y1+b) and x2==(x1+a)):
        canmove = True
        break;
      else:
        canmove = False
    if canmove ==True:
      break;


  if(checkerboard[x2][y2] !=0 or checkerboard[x1][y1]!=1):
      canmove = False


  if(canmove ==True):
      temp = checkerboard[x2][y2]
      checkerboard[x2][y2] = checkerboard[x1][y1]
      checkerboard[x1][y1] = temp

  if(canmove ==True):
      print("Yes")
  else:
      print("No")
def bishop(postion1,postion2,checkerboard):
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
  dif = x2 - x1

  if((y1+dif) == y2 and dif>0):
    for a in range(1,dif+1):
      if(checkerboard[x1+a][y1+a] !=0):
        canmove = False

        break
      else:
        canmove = True
  if((y1+dif) == y2 and dif<0):

    for a in range(-1,dif-1,-1):

      if(checkerboard[x1+a][y1+a] !=0):
        canmove = False
        break

      else:
        canmove = True
  if(canmove ==True):
      print("Yes")
  else:
      print("No")


def castle(postion1,postion2,checkerboard):
  x1 = int(postion1[0])
  y1 = int(postion1[1])
  x2 = int(postion2[0])
  y2 = int(postion2[1])
  canmove = True
  if x1 == x2:
    step = 1 if y2 > y1 else -1
    for a in range(y1 + step, y2, step):
      if checkerboard[x1][a] != 0:
        canmove = False
        break


  elif y1 == y2:
    step = 1 if x2 > x1 else -1
    for a in range(x1 + step, x2, step):
      if checkerboard[a][y1] != 0:
        canmove = False
        break
  if(canmove ==True):
      print("Yes")
  else:
      print("No")
checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]
piece = input()
postion1 = input().split()
postion2 = input().split()
if(piece == "皇后"):
  queen(postion1,postion2,checkerboard)
elif(piece == "士兵"):
  pawn(postion1,postion2,checkerboard)
elif(piece == "騎士"):
  knight(postion1,postion2,checkerboard)
elif(piece == "國王"):
  king(postion1,postion2,checkerboard)
elif(piece == "主教"):
  bishop(postion1,postion2,checkerboard)
elif(piece == "城堡"):
  castle(postion1,postion2,checkerboard)